{
 "title": "dcm bitrate monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "port",
    "query": "label_values(dcm_port_bitrate,port)"
   },
   { "name": "bitrateThreshold", "label": "bitrate threshold", "query": "1.5" }
  ]
 },
 "panels": [
  {
   "title": "input port count",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(dcm_port_input > $bitrateThreshold)"
    }
   ]
  },
  {
   "title": "output bitrate count",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(dcm_port_output > $bitrateThreshold)"
    }
   ]
  },
  {
   "title": "dcm input",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dcm_port_bitrate{port=~\"$port\",type=\"input\"}"
    }
   ]
  },
  {
   "title": "dcm output",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dcm_port_bitrate{port=~\"$port\",type=\"output\"}"
    }
   ]
  },
  {
   "title": "port table",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "targets": [
    { "expr": "dcm_port_input{}+0" },
    { "expr": "dcm_port_output{}+0" }
   ]
  }
 ]
}